# Generated by Django 5.2.5 on 2026-09-07 03:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='target_role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Network Engineer', 'Network Engineer'), ('Engineering Manager', 'Engineering Manager'), ('Penetration Tester / Ethical Hacker', 'Penetration Tester / Ethical Hacker'), ('Scrum Master / Agile Coach', 'Scrum Master / Agile Coach'), ('Solutions Architect', 'Solutions Architect'), ('Platform Engineer', 'Platform Engineer'), ('Database Administrator (DBA)', 'Database Administrator (DBA)'), ('Blockchain / Smart Contract Developer', 'Blockchain / Smart Contract Developer'), ('MLOps Engineer', 'MLOps Engineer'), ('Computer Vision Engineer', 'Computer Vision Engineer'), ('Game Developer', 'Game Developer'), ('Data Scientist', 'Data Scientist'), ('Sales / Solutions Engineer', 'Sales / Solutions Engineer'), ('Technical Product Manager', 'Technical Product Manager'), ('Security Operations (SOC) Analyst', 'Security Operations (SOC) Analyst'), ('UX/UI Designer', 'UX/UI Designer'), ('Business Intelligence (BI) Analyst', 'Business Intelligence (BI) Analyst'), ('Data Engineer', 'Data Engineer'), ('NLP Engineer', 'NLP Engineer'), ('Test Automation Engineer', 'Test Automation Engineer'), ('Cloud Infrastructure Engineer', 'Cloud Infrastructure Engineer'), ('Fraud Analyst', 'Fraud Analyst'), ('Site Reliability Engineer (SRE)', 'Site Reliability Engineer (SRE)'), ('DevOps Engineer', 'DevOps Engineer'), ('Mobile App Developer (iOS/Android)', 'Mobile App Developer (iOS/Android)'), ('QA Engineer', 'QA Engineer'), ('Robotics Engineer', 'Robotics Engineer'), ('Frontend Developer', 'Frontend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('AI/ML Engineer', 'AI/ML Engineer'), ('Backend Developer', 'Backend Developer'), ('IoT Solutions Engineer', 'IoT Solutions Engineer'), ('Application Security (AppSec) Engineer', 'Application Security (AppSec) Engineer'), ('Data Analyst', 'Data Analyst'), ('Embedded Systems Developer', 'Embedded Systems Developer'), ('Systems Analyst', 'Systems Analyst'), ('QA Automation Engineer', 'QA Automation Engineer'), ('SDET (Software Development Engineer in Test)', 'SDET (Software Development Engineer in Test)')], max_length=150), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primary_role',
            field=models.CharField(blank=True, choices=[('Network Engineer', 'Network Engineer'), ('Engineering Manager', 'Engineering Manager'), ('Penetration Tester / Ethical Hacker', 'Penetration Tester / Ethical Hacker'), ('Scrum Master / Agile Coach', 'Scrum Master / Agile Coach'), ('Solutions Architect', 'Solutions Architect'), ('Platform Engineer', 'Platform Engineer'), ('Database Administrator (DBA)', 'Database Administrator (DBA)'), ('Blockchain / Smart Contract Developer', 'Blockchain / Smart Contract Developer'), ('MLOps Engineer', 'MLOps Engineer'), ('Computer Vision Engineer', 'Computer Vision Engineer'), ('Game Developer', 'Game Developer'), ('Data Scientist', 'Data Scientist'), ('Sales / Solutions Engineer', 'Sales / Solutions Engineer'), ('Technical Product Manager', 'Technical Product Manager'), ('Security Operations (SOC) Analyst', 'Security Operations (SOC) Analyst'), ('UX/UI Designer', 'UX/UI Designer'), ('Business Intelligence (BI) Analyst', 'Business Intelligence (BI) Analyst'), ('Data Engineer', 'Data Engineer'), ('NLP Engineer', 'NLP Engineer'), ('Test Automation Engineer', 'Test Automation Engineer'), ('Cloud Infrastructure Engineer', 'Cloud Infrastructure Engineer'), ('Fraud Analyst', 'Fraud Analyst'), ('Site Reliability Engineer (SRE)', 'Site Reliability Engineer (SRE)'), ('DevOps Engineer', 'DevOps Engineer'), ('Mobile App Developer (iOS/Android)', 'Mobile App Developer (iOS/Android)'), ('QA Engineer', 'QA Engineer'), ('Robotics Engineer', 'Robotics Engineer'), ('Frontend Developer', 'Frontend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('AI/ML Engineer', 'AI/ML Engineer'), ('Backend Developer', 'Backend Developer'), ('IoT Solutions Engineer', 'IoT Solutions Engineer'), ('Application Security (AppSec) Engineer', 'Application Security (AppSec) Engineer'), ('Data Analyst', 'Data Analyst'), ('Embedded Systems Developer', 'Embedded Systems Developer'), ('Systems Analyst', 'Systems Analyst'), ('QA Automation Engineer', 'QA Automation Engineer'), ('SDET (Software Development Engineer in Test)', 'SDET (Software Development Engineer in Test)')], max_length=150),
        ),
    ]
