# Generated by Django 5.2.5 on 2026-09-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatmessage_user_content_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='use_case',
            field=models.CharField(choices=[('general_chat', 'General Chat'), ('career_guidance', 'Career Guidance'), ('interview_assessment', 'Interview Assessment')], default='general_chat', max_length=30),
        ),
    ]
