# Generated by Django 5.2.5 on 2026-09-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_interview_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_answer', models.TextField(blank=True, null=True)),
                ('candidate_answer', models.TextField(blank=True, null=True)),
                ('question_difficulty', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedbacks', to='chats.chatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedbacks', to='chats.chatsession')),
            ],
            options={
                'unique_together': {('session', 'message')},
            },
        ),
    ]
