# Generated by Django 5.2.5 on 2026-09-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_interviewfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='candidate_answer',
        ),
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='question_answer',
        ),
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='question_difficulty',
        ),
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='question_text',
        ),
    ]
