# Generated by Django 5.2.5 on 2026-08-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_simpletextembedding'),
    ]

    operations = [
    migrations.RunSQL(
        """
        ALTER TABLE common_simpletextembedding
        ALTER COLUMN embedding TYPE vector(768)
        USING NULL;
        """,
        reverse_sql="""
        ALTER TABLE common_simpletextembedding
        ALTER COLUMN embedding TYPE jsonb
        USING '[]'::jsonb;
        """,
    ),
]
