# Generated by Django 5.2.5 on 2026-09-03 06:23

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_simpletextembedding_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpletextembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
