# Generated by Django 5.2.5 on 2026-09-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_simpletextembedding_embedding'),
        ('common', '0007_document_source_interviewquestions'),
    ]

    operations = [
    ]
