# Generated by Django 5.2.5 on 2026-09-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_document_source_interviewquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestions',
            name='experience',
            field=models.CharField(choices=[('none', 'None'), ('intern', 'Intern'), ('junior', 'Junior'), ('mid_level', 'Mid-level'), ('senior', 'Senior'), ('any', 'Any')], db_index=True, max_length=50),
        ),
    ]
