# Generated by Django 5.2.5 on 2026-09-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_interviewquestions_experience'),
        ('common', '0008_merge_20260904_2103'),
    ]

    operations = [
    ]
