# Generated by Django 5.2.5 on 2026-09-06 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatsession_use_case'),
        ('common', '0009_merge_20260905_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.interviewquestions')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='chats.chatsession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
